version: '3'
services:
    recommender:
        build:
            context: './recommender'
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./recommender:/home/python/app
        container_name: clickbait-recommender
        expose:
            - '5002'
        ports:
            - '5002:5002'
        command: python3 app.py

    user:
        build:
            context: './user'
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./user/src:/home/node/app/src
            - ./user/nodemon.json:/home/node/app/nodemon.json
        container_name: clickbait-users
        expose:
            - '4003'
        ports:
            - '4003:4003'
        command: yarn dev

    web:
        build:
            context: './web'
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./web:/home/node/app
        container_name: clickbait-web
        expose:
            - '3000'
        ports:
            - '3000:3000'
        command: yarn dev
        depends_on:
            - recommender
            - user

    nginx:
        image: nginx:latest
        ports:
            - '8080:8080'
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
            - recommender
            - user
