version: '3'
services:
    web:
        build: './web'
        command: yarn dev
        ports:
            - '3000:3000'

    server:
        build: './server'
        ports:
            - '5002:5002'

    nginx:
        image: nginx:latest
        ports:
            - '8080:8080'
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
            - server
